import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import * as DocumentPicker from 'expo-document-picker';
import { getDb } from '../../db/client';
import { listActivities } from '../../db/queries/activities';
import type { Db } from '../../db/client';
import { Platform } from 'react-native';
import { ANDROID_DATABASE_PATH, IOS_LIBRARY_PATH } from '@op-engineering/op-sqlite';

function getDbPath(): string {
  const dbName = 'movement_tracker.db';
  if (Platform.OS === 'ios') {
    return `file://${IOS_LIBRARY_PATH}/LocalDatabase/${dbName}`;
  }
  return `file://${ANDROID_DATABASE_PATH}/${dbName}`;
}

export async function exportData(): Promise<boolean> {
  try {
    const db = getDb();
    const activities = await listActivities(db, { limit: 10000 });
    
    const dbPath = getDbPath();
    
    const exists = await FileSystem.getInfoAsync(dbPath);
    if (!exists.exists) {
      console.warn('Database file not found at:', dbPath);
      return false;
    }

    const exportPath = `${FileSystem.documentDirectory}running_tracker_backup_${Date.now()}.db`;
    await FileSystem.copyAsync({ from: dbPath, to: exportPath });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(exportPath, {
        mimeType: 'application/x-sqlite3',
        dialogTitle: 'Export Movement Tracker Backup',
      });
      return true;
    } else {
      console.warn('Sharing not available on this device');
      return false;
    }
  } catch (err) {
    console.error('Export failed:', err);
    return false;
  }
}

export async function importData(): Promise<boolean> {
  try {
    const result = await DocumentPicker.getDocumentAsync({
      type: '*/*',
      copyToCacheDirectory: true,
    });

    if (result.canceled || !result.assets || result.assets.length === 0) {
      return false;
    }

    const file = result.assets[0];
    if (!file.name.endsWith('.db')) {
      alert('Please select a valid .db backup file generated by Movement Tracker.');
      return false;
    }

    const dbPath = getDbPath();

    await FileSystem.copyAsync({ from: file.uri, to: dbPath });
    
    return true;
  } catch (err) {
    console.error('Import failed:', err);
    return false;
  }
}
