import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import * as DocumentPicker from 'expo-document-picker';
import { getDb, closeDb, reopenDb } from '../../db/client';
import { listActivities } from '../../db/queries/activities';
import { Platform } from 'react-native';
import { ANDROID_DATABASE_PATH, IOS_LIBRARY_PATH } from '@op-engineering/op-sqlite';

function getDbPath(): string {
  const dbName = 'movement_tracker.db';
  if (Platform.OS === 'ios') {
    return `file://${IOS_LIBRARY_PATH}/LocalDatabase/${dbName}`;
  }
  return `file://${ANDROID_DATABASE_PATH}/${dbName}`;
}

export async function exportData(): Promise<boolean> {
  try {
    const db = getDb();
    await listActivities(db, { limit: 10000 });

    const dbPath = getDbPath();

    const exists = await FileSystem.getInfoAsync(dbPath);
    if (!exists.exists) {
      console.warn('Database file not found at:', dbPath);
      return false;
    }

    const exportPath = `${FileSystem.documentDirectory}running_tracker_backup_${Date.now()}.db`;
    await FileSystem.copyAsync({ from: dbPath, to: exportPath });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(exportPath, {
        mimeType: 'application/x-sqlite3',
        dialogTitle: 'Export Movement Tracker Backup',
      });
      return true;
    } else {
      console.warn('Sharing not available on this device');
      return false;
    }
  } catch (err) {
    console.error('Export failed:', err);
    return false;
  }
}

export async function importData(): Promise<boolean> {
  try {
    const result = await DocumentPicker.getDocumentAsync({
      type: '*/*',
      copyToCacheDirectory: true,
    });

    if (result.canceled || !result.assets || result.assets.length === 0) {
      return false;
    }

    const file = result.assets[0];
    if (!file.name.endsWith('.db')) {
      alert('Please select a valid .db backup file generated by Movement Tracker.');
      return false;
    }

    const dbPath = getDbPath();

    // 1. Gracefully close the live connection before touching the file on disk.
    closeDb();

    // 1.5 Explicitly delete the old file so copyAsync doesn't silently fail.
    try {
      await FileSystem.deleteAsync(dbPath, { idempotent: true });
    } catch (e) {
      console.warn('Failed to delete old DB, continuing anyway:', e);
    }

    // 2. Overwrite the database file with the selected backup.
    await FileSystem.copyAsync({ from: file.uri, to: dbPath });

    // 3. Re-open the connection immediately — migrations run, new data is live.
    reopenDb();

    return true;
  } catch (err) {
    console.error('Import failed:', err);
    // Always ensure a working DB connection is restored, even on failure.
    try { reopenDb(); } catch (_) {}
    return false;
  }
}
